-- Your SQL goes here
CREATE TABLE category(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  status INTEGER NOT NULL DEFAULT 1, 
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP
);

CREATE TABLE product (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(100),
  price REAL NOT NULL,
  photo VARCHAR(100),
  category_id INTEGER,
  status INTEGER NOT NULL DEFAULT 1, 
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES Category(id)
);